### ISSUE TITLE
Modify Progress Report extensively

### ISSUE THREAD

**Issue by imrryr** [memphis-iis/mofacts-ies#467]
Here is the screenshot, please ask questions as needed. I will add details in comments also.

![image](https://user-images.githubusercontent.com/13023147/145584535-5b53b13e-029c-4a19-a853-40ac5a732eb1.png)

**Comment by imrryr** [comment]
So, it occurs to me the progress reporter should be unavailable in some learning systems like Meng's. Do we support that? 

If not let's do it like this if the progressReporter tag for a unit is not provided then no progress report for the unit will be provided (button hidden). 

If it is provided it will need to be 6 numbers comma separated, which are the 6 values I highlighted in yellow in the figure.

"progressReporter": ".7,30,60,30,90,60"

We could make it more complex, but added function won't really be needed at the current time.

**Comment by imrryr** [comment]
I labeled this a feature, despite the freeze, due to the importance of getting this right. It should go into postgresmigration though, since this feature is an exception to the freeze.

**Comment by imrryr** [comment]
Also, the speed of learning dial should have the colors reverses (high speed is red, low speed is green). There will be no numbers on that graph, but we could label it 0 to max....

**Comment by JRustyHaner** [comment]
![image](https://user-images.githubusercontent.com/46696077/148266860-83c0d295-00d1-417c-8946-2242b39a20e0.png)
This is the current progress report front end. It's already been configured for the Min/Max of each gauge. The next step is to get fill in the calculations.

**Comment by JRustyHaner** [comment]
@imrryr I have plugged in the calculations for speed of learning and difficulty.  I have some questions on making sure the calculations are as expected. The rate of item introduction in this case can be defined as the amount of new stims per stims attempted (maximum 30), correct? 

Also, do we have a definition of a mastered item?

**Comment by imrryr** [comment]
Any item introduced will be considered mastered, since if it is introduced it should be repeated and stay at high probability. So that is super simple, it is all items with 1 or more prior practices.

**Comment by imrryr** [comment]
For the speed of learning gauge, it is just the natural log of 1 + the count of items introduced in the last 30. So the minimum is 0 and the maximum is natural log of 31, I.e. 3.43

Please continue to ask questions unless I am crystal clear

**Comment by imrryr** [comment]
Some bugs here. My performance was 71.88 percent, so the bottom graph should read slightly too easy.... since the calculation is .7-.7188 = -.0188, which is right in the center nearly since the gauge is from -.3 to .3

The calculations seem to indicate 30 items, but the number of items is actually 60. We need to count items for both the number mastered and the number possible. These are stims, not clusters, we are counting.

Also, can we add the tooltips originally specified above?


![mofacts_app and 13 more pages - Personal - Microsoft​ Edge 1_21_2022 11_14_55 AM](https://user-images.githubusercontent.com/13023147/150570725-ff463d47-3844-43ed-a05f-5810bdcd0876.png)

**Comment by JRustyHaner** [comment]
@imrryr  the 30 items is because the calculations are being done on the last 30 trials.  The tooltips are fairly easy. I'll take a look at the difficulty as well

**Comment by imrryr** [comment]
The first graph was never supposed to be for the last 30... its kinda not what I want then. The gauge tells the student how many are mastered from the full set of 60, by checking all the items to see which have had responses. Sorry, I thought that was clear, but evidently I had a blind spot. It should help the student see how much longer they need to practice in concrete terms. Can we fix it please?

**Comment by imrryr** [comment]
Also, I assume this is not implemented yet? "progressReporter": ".7,30,60,30,90,60"

You might note that there was no parameter specified for the mastered items gauge because it can't be parameterized in a meaningful way since it is always "total introduced items of total items"

**Comment by imrryr** [comment]
![mofacts_app and 6 more pages - Personal - Microsoft​ Edge 2_7_2022 7_17_34 PM](https://user-images.githubusercontent.com/13023147/152899880-12f4e849-f095-4840-b0dc-d6cf6766896e.png)

**Comment by imrryr** [comment]
Speed of learning graph is busted. If about 24 items have been introduced in 30 trials it would read around 3, which is in the red...

Difficulty graph is reseversed.... I was at about 75% which should be too easy, the original spec had easy on right hard on left (also please reduce fontsize on "Hover" statements, and also, not "Hover for, ... Hover over...

**Comment by imrryr** [comment]
Messages under speed of learning dial are missing.

**Comment by JRustyHaner** [comment]
@imrryr  Speed of learning is currently defined as:
speedOfLearning = Math.log(1+ speedOfLearningData.stimsIntroduced / totalPracticeDuration) * 100; I wonder if it's a PEMDAS issue.

**Comment by imrryr** [comment]
But that definition is completely wrong you see. You just take the natural log of the number of items introduced in the last 30 trials... There is no time involved

**Comment by JRustyHaner** [comment]
@imrryr the reversal issue was solved fairly easy. The hover statement sizes are set by the browser. It'll appear differently in Firefox, Safari, since its just using the browser's internal tooltip system.

**Comment by imrryr** [comment]
Plus one otherwise you could take the log of zero

**Comment by imrryr** [comment]
I'm talking about the note underneath the place where you hover not the statement. The note itself is too large and has a grammar error.

**Comment by JRustyHaner** [comment]
@imrryr that makes more sense, and easily fixed on the speedOfLearning issue. The grammar error and the font size are fixed then.

**Comment by imrryr** [comment]
Speed of learning graph is still missing the statements underneath as shown in spec...  these statements are already there as of earlier testing, but are now missing. See the post 18 days previously on this thread.

**Comment by imrryr** [comment]
The statements below "too easy" and "too hard" are still the same size as the hover statements below these tooltip spots. You reduced fontsize for the "too easy and too hard" in addition to the statement, but only the hover statement was to be reduced.

**Comment by imrryr** [comment]
A third little detail here: In the Progress section, regarding the Difficulty dial, when I hovered over the text "Too Easy", it showed the description of "MoFaCTS thinks its choices have been too hard"; when I hovered over the text "Too Hard", it showed the description of "MoFaCTS thinks its choices have been too easy".

**Comment by imrryr** [comment]
By the way, thanks again for adding the new progress reporter, its really nice!

**Comment by JRustyHaner** [comment]
@imrryr The default setting for the text under the speed of learning (unless set in the TDF) is 60 for the first and 90 for the second. I can't reproduce on my end. However, the other changes have been made.

**Comment by imrryr** [comment]
Ah I see my confusion now I just didn't have enough trials....

**Comment by imrryr** [comment]
Please close this after the other things are taken care of then
